# -*- mode: ruby -*-
# vi: set ft=ruby :

# TODO 
# this software does NOT reliably work for linux yet

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
    hostname = "linbox"
    locale = "en_GB.UTF.8"

    config.vm.box = "ubuntu/trusty64"
  
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 4
    end
  
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get upgrade -y
  
      sudo apt-get install -y git curl python3
  
      curl -sSL https://install.python-poetry.org | python3 -
  
      cd /home/vagrant
      git clone https://github.com/0xSolanaceae/proXXy.git
    SHELL
  end