# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|

    hostname = "winbox"
    locale = "en_GB.UTF.8"

    config.vm.box = "peru/windows-10-enterprise-x64-eval"

    config.vm.provider "libvirt" do |v|
        v.memory = 2048
        v.cpus = 4
    end
    
    config.vm.provision "shell", inline: <<-SHELL
        $env:PYTHON_KEYRING_BACKEND="keyring.backends.null.Keyring" # see https://stackoverflow.com/questions/74392324/poetry-install-throws-winerror-1312-when-running-over-ssh-on-windows-10
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        
        # upgrade choco
        choco upgrade chocolatey -y
        choco config set commandExecutionTimeoutSeconds 2700

        # dev tools
        $ErrorActionPreference = 'Stop'
        $maxRetries = 3
        $retryCount = 0
        while ($retryCount -lt $maxRetries) {
            try {
                choco install git -y
                choco install python -y
                pip install pipx
                pipx ensurepath
                pipx install poetry # if this fails, refer to line 19
                # or put this in cmd:
                # SET PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
                break
            } catch {
                Write-Host "Installation failed, retrying..."
                $retryCount++
                Start-Sleep -Seconds 10
            }
        }
        
        # pip update
        python.exe -m pip install --upgrade pip

        # clone repo
        cd C:\\Users\\vagrant\\Desktop
        try {
            git clone https://github.com/0xSolanaceae/proXXy.git
        } catch {
            Write-Host "Clone failed, continuing..."
        }

    SHELL
end