name: Linux Retrieval

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run script
      run: |
        poetry run python proXXy.py

    - name: Validate proxies
      run: |
        poetry run python proXXy.py --validate

    - name: Print invalid sources
      run: |
        cat validated/INVALID.yaml
      
    - name: Print valid sources
      run: |
        cat validated/VALID.yaml

    - name: HTTP output
      run: |
        cat output/HTTP.txt

    - name: HTTPS output
      run: |
        cat output/HTTPS.txt

    - name: SOCKS4 output
      run: |
        cat output/SOCKS4.txt
      
    - name: SOCKS5 output
      run: |
        cat output/SOCKS5.txt